### ISSUE TITLE
hi help please... can't build wheels

### ISSUE THREAD

**Issue by Akilak11** [CNES/Pandora_libSGM#1]
C:\webui_forge_cu121_torch251\system\python>pip install libSGM==0.4.7
Collecting libSGM==0.4.7
  Using cached libsgm-0.4.7.tar.gz (488 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<2.0 in c:\users\andrii\appdata\local\programs\python\python310\lib\site-packages (from libSGM==0.4.7) (1.26.4)
Requirement already satisfied: numba>=0.55.2 in c:\users\andrii\appdata\local\programs\python\python310\lib\site-packages (from libSGM==0.4.7) (0.60.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\andrii\appdata\local\programs\python\python310\lib\site-packages (from numba>=0.55.2->libSGM==0.4.7) (0.43.0)
Building wheels for collected packages: libSGM
  Building wheel for libSGM (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for libSGM (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [139 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-310\libsgm_python
      copying src\libsgm_python\lr_manager.py -> build\lib.win-amd64-cpython-310\libsgm_python
      copying src\libsgm_python\sgm_python.py -> build\lib.win-amd64-cpython-310\libsgm_python
      copying src\libsgm_python\sgm_python_parall.py -> build\lib.win-amd64-cpython-310\libsgm_python
      copying src\libsgm_python\__init__.py -> build\lib.win-amd64-cpython-310\libsgm_python
      running build_ext
      building 'libSGM.sgm_wrapper' extension
      creating build\temp.win-amd64-cpython-310\Release\src\libSGM\lib
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Andrii\AppData\Local\Temp\pip-build-env-sqy00nim\overlay\Lib\site-packages\numpy\_core\include -Isrc/libSGM/lib/ -IC:\Users\Andrii\AppData\Local\Programs\Python\Python310\include -IC:\Users\Andrii\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsrc/libSGM/lib/sgm.cpp /Fobuild\temp.win-amd64-cpython-310\Release\src/libSGM/lib/sgm.obj -O3 -fopenmp -std=c++11
      cl: Є®¬ ­¤­ п бва®Є  warning D9002: Їа®ЇгбЄ ­ҐЁ§ўҐбв­®Ј® Ї а ¬Ґва  "-O3"
      cl: Є®¬ ­¤­ п бва®Є  warning D9002: Їа®ЇгбЄ ­ҐЁ§ўҐбв­®Ј® Ї а ¬Ґва  "-fopenmp"
      cl: Є®¬ ­¤­ п бва®Є  warning D9002: Їа®ЇгбЄ ­ҐЁ§ўҐбв­®Ј® Ї а ¬Ґва  "-std=c++11"
      sgm.cpp
      src/libSGM/lib/sgm.cpp(110): warning C4018: <: ­Ґб®®вўҐвбвўЁҐ вЁЇ®ў б® §­ Є®¬ Ё ЎҐ§ §­ Є
      src/libSGM/lib/sgm.cpp(110): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(726): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "CostVolumes sgm<uint8_t>(uint8_t *,uint8_t *,uint8_t *,int *,unsigned long,unsigned long,unsigned int,uint8_t,float *,bool,bool)"
      src/libSGM/lib/sgm.cpp(112): warning C4018: <: ­Ґб®®вўҐвбвўЁҐ вЁЇ®ў б® §­ Є®¬ Ё ЎҐ§ §­ Є
      src/libSGM/lib/sgm.cpp(128): warning C4018: <: ­Ґб®®вўҐвбвўЁҐ вЁЇ®ў б® §­ Є®¬ Ё ЎҐ§ §­ Є
      src/libSGM/lib/sgm.cpp(250): warning C4018: <: ­Ґб®®вўҐвбвўЁҐ вЁЇ®ў б® §­ Є®¬ Ё ЎҐ§ §­ Є
      src/libSGM/lib/sgm.cpp(366): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(366): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(726): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "CostVolumes sgm<uint8_t>(uint8_t *,uint8_t *,uint8_t *,int *,unsigned long,unsigned long,unsigned int,uint8_t,float *,bool,bool)"
      src/libSGM/lib/sgm.cpp(134): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromTopLeft0<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,T *,float,float,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(413): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(413): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(139): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromTopLeft1<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,T *,float,float *,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(461): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(461): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(144): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromTopLeft2<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,T *,T *,float,float *,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(509): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(509): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(149): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromTopLeft3<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,float,float *,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(554): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(554): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(257): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromBottomRight4<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,T *,float,float,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(601): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(601): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(262): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromBottomRight5<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,T *,float,float *,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(650): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(650): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(267): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromBottomRight6<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,T *,T *,float,float *,float &)"
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(699): warning C4244: +=: ЇаҐ®Ўа §®ў ­ЁҐ "float" ў "T", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
              with
              [
                  T=uint8_t
              ]
      src/libSGM/lib/sgm.cpp(699): note: Є®­вҐЄбв б®§¤ ­Ёп нЄ§Ґ¬Ї«па  и Ў«®­  (б­ з «  б ¬л© бв ал©)
      src/libSGM/lib/sgm.cpp(272): note: ўлЇ®«­пҐвбп Є®¬ЇЁ«пжЁп ббл«ЄЁ ­  нЄ§Ґ¬Ї«па и Ў«®­ дг­ЄжЁЁ "T aggregatedCostFromBottomRight7<T>(T,int,int,int,T,int,int,int,T,T,Direction,T *,T *,float,float *,float &)"
              with
              [
                  T=uint8_t
              ]
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Andrii\AppData\Local\Temp\pip-build-env-sqy00nim\overlay\Lib\site-packages\numpy\_core\include -Isrc/libSGM/lib/ -IC:\Users\Andrii\AppData\Local\Programs\Python\Python310\include -IC:\Users\Andrii\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsrc/libSGM/sgm_wrapper.cpp /Fobuild\temp.win-amd64-cpython-310\Release\src/libSGM/sgm_wrapper.obj -O3 -fopenmp -std=c++11
      cl: Є®¬ ­¤­ п бва®Є  warning D9002: Їа®ЇгбЄ ­ҐЁ§ўҐбв­®Ј® Ї а ¬Ґва  "-O3"
      cl: Є®¬ ­¤­ п бва®Є  warning D9002: Їа®ЇгбЄ ­ҐЁ§ўҐбв­®Ј® Ї а ¬Ґва  "-fopenmp"
      cl: Є®¬ ­¤­ п бва®Є  warning D9002: Їа®ЇгбЄ ­ҐЁ§ўҐбв­®Ј® Ї а ¬Ґва  "-std=c++11"
      sgm_wrapper.cpp
      C:\Users\Andrii\AppData\Local\Temp\pip-build-env-sqy00nim\overlay\Lib\site-packages\numpy\_core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      src/libSGM/sgm_wrapper.cpp(3836): warning C4244: =: ЇаҐ®Ўа §®ў ­ЁҐ "long" ў "char", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4400): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "unsigned int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4400): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "unsigned long", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4400): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "unsigned long", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4421): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4421): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4421): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4501): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4501): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4944): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "unsigned int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4944): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "unsigned long", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4944): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "unsigned long", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4965): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4965): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(4965): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(5045): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(5045): warning C4244:  аЈг¬Ґ­в: ЇаҐ®Ўа §®ў ­ЁҐ "Py_ssize_t" ў "int", ў®§¬®¦­  Ї®вҐап ¤ ­­ле
      src/libSGM/sgm_wrapper.cpp(5766): error C2039: "subarray": ­Ґ пў«пҐвбп з«Ґ­®¬ "_PyArray_Descr".
      C:\Users\Andrii\AppData\Local\Temp\pip-build-env-sqy00nim\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h(618): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_PyArray_Descr"
      src/libSGM/sgm_wrapper.cpp(5767): error C2039: "subarray": ­Ґ пў«пҐвбп з«Ґ­®¬ "_PyArray_Descr".
      C:\Users\Andrii\AppData\Local\Temp\pip-build-env-sqy00nim\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h(618): note:  б¬. ®Ўкпў«Ґ­ЁҐ "_PyArray_Descr"
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libSGM
Failed to build libSGM
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (libSGM)

C:\webui_forge_cu121_torch251\system\python>pip install libSGM==0.4.6
Collecting libSGM==0.4.6
  Downloading libsgm-0.4.6.tar.gz (485 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-i50347ex\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-i50347ex\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-i50347ex\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\os.py", line 685, in __setitem__
          value = self.encodevalue(value)
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\os.py", line 743, in check_str
          raise TypeError("str expected, not %s" % type(value).__name__)
      TypeError: str expected, not NoneType
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\webui_forge_cu121_torch251\system\python>pip install libSGM==0.3.1
Collecting libSGM==0.3.1
  Downloading libSGM-0.3.1.tar.gz (153 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]

      WARNING ! Installation of numpy is required before libSGM installation

      Traceback (most recent call last):
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-6c3h4aag\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-6c3h4aag\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-6c3h4aag\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-6c3h4aag\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\webui_forge_cu121_torch251\system\python>pip install libSGM==0.2.1
Collecting libSGM==0.2.1
  Downloading libSGM-0.2.1.tar.gz (445 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]

      WARNING ! Installation of numpy is required before libSGM installation

      Traceback (most recent call last):
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Andrii\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-b49dejg9\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-b49dejg9\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-b49dejg9\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Andrii\AppData\Local\Temp\pip-build-env-b49dejg9\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\webui_forge_cu121_torch251\system\python>pip install libsgm_python
ERROR: Could not find a version that satisfies the requirement libsgm_python (from versions: none)
ERROR: No matching distribution found for libsgm_python

C:\webui_forge_cu121_torch251\system\python>

**Comment by steuxyo** [comment]
Hello,

I see you are installing plugin libsgm with:
* python 3.10
* libsgm==0.4.7


There are currently some issues with libsgm 0.4.7

As you are using python 3.10, you should force installation of libsgm==0.4.6.


A new release of libsgm will be available at the end of November,  fixing all installation issues.


If you still encounter issue, it might be caused by your distribution. In this case, you will have to build libsgm like this:

*  git clone https://github.com/CNES/Pandora_libSGM.git
* git checkout 0.4.6
*  //Generate a virtualenv with python 3.10 : python3.10-dev must be installed
*  //Source your virtualenv
* pip install --upgrade numpy
* python setup.py build_ext

**Comment by Akilak11** [comment]
I installed - thak you.

**Comment by duboise-cnes** [comment]
Seems ok with @steuxyo help. I close the issue. python3.10 is now available
